Add clickOverflowHidden test
Calling WebElement.click() on element with overflow hidden throws in
Safari driver:
ElementNotVisibleError: An element command could not be completed
because the element is not visible on the page.